### ISSUE TITLE
Continues to crash

### ISSUE THREAD

**Issue by IthildinX** [Zzm317/homebridge-re-yeelight#16]
After I get token from miio2.db and type into the config.json for homebridge-re-yeelight.
My homebridge continues to crash.

Did I do something wrong?

Following is the platform in config.json and the error message
    {
        "platform": "ReYeelightPlatform",
        "deviceCfgs": [{
            "type": "CeilingLamp",
            "ip": "192.168.5.177",
            "token": "234ac42e01a5dba7ace0f372c0ae8fb2",
            "Name": "Ceiling Lamp",
            "updatetimer": true,
            "interval": 5
        }]
    },

[2018-7-15 00:32:36] [ReYeelightPlatform] Initializing ReYeelightPlatform platform...
[2018-7-15 00:32:36] [ReYeelightPlatform] [INFO]*********************************************************************
[2018-7-15 00:32:36] [ReYeelightPlatform] [INFO]*                         ReYeelight v0.0.11                         *
[2018-7-15 00:32:36] [ReYeelightPlatform] [INFO]*    GitHub: https://github.com/Zzm317/homebridge-re-yeelight       *
[2018-7-15 00:32:36] [ReYeelightPlatform] [INFO]*                        QQ Group:545171648                         *
[2018-7-15 00:32:36] [ReYeelightPlatform] [INFO]*    Telegram Group:https://t.me/joinchat/EujYfA-JKSwpRlXURD1t6g    *
[2018-7-15 00:32:36] [ReYeelightPlatform] [INFO]*********************************************************************
[2018-7-15 00:32:36] [ReYeelightPlatform] [INFO]start success...

C:\Users\Ithildin\AppData\Roaming\npm\node_modules\homebridge-re-yeelight\Devices\CeilingLamp.js:16
    this.device = new miio.Device({
                  ^
TypeError: miio.Device is not a constructor
    at new YeCeilingLamp (C:\Users\Ithildin\AppData\Roaming\npm\node_modules\homebridge-re-yeelight\Devices\CeilingLamp.js:16:19)
    at ReYeelightPlatform.accessories (C:\Users\Ithildin\AppData\Roaming\npm\node_modules\homebridge-re-yeelight\index.js:102:21)
    at Server._loadPlatformAccessories (C:\Users\Ithildin\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:385:20)
    at Server._loadPlatforms (C:\Users\Ithildin\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:329:16)
    at Server.run (C:\Users\Ithildin\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:85:36)
    at module.exports (C:\Users\Ithildin\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:43:10)
    at Object.<anonymous> (C:\Users\Ithildin\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by Zzm317** [comment]
use miio@0.14.1

**Comment by IthildinX** [comment]
Thanks, after install miio@0.14.1, the ReYeelightPlatform is worked.
However, it made the homebridge failed to discover Mi Air Purifier.
Is there any way to use the old and new miio together?
