### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by paloga85** [Zzm317/homebridge-re-yeelight#18]
/usr/local/lib/node_modules/homebridge-re-yeelight/Devices/ColorLEDBulb.js:17
    this.device = new miio.Device({
                  ^

TypeError: miio.Device is not a constructor
    at new YeColorLEDBulb (/usr/local/lib/node_modules/homebridge-re-yeelight/Devices/ColorLEDBulb.js:17:19)
    at ReYeelightPlatform.accessories (/usr/local/lib/node_modules/homebridge-re-yeelight/index.js:90:21)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:386:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:330:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
How can i fix this?

**Comment by Zzm317** [comment]
use miio@0.14.1
