### ISSUE TITLE
Backtrace error

### ISSUE THREAD

**Issue by JrCs** [Zzm317/homebridge-re-yeelight#5]
Hi,
i have configured my ColorLedBulb as this
```json
  "platforms": [
    {
      "platform": "ReYeelightPlatform",
      "deviceCfgs": [
        {
          "type": "ColorLEDBulb",
          "ip": "10.16.0.120",
          "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "Name": "LED Bulb",
          "updatetimer": true,
          "interval": 5
        }
      ]
    }
  ]
```
I get the token from `miio discover` during the init phase.
When i start `homebridge` i have an error with a backtrace:
```
Including environment variables from /root/.homebridge/.env.
Environment is set to 'debug'.
Force the installation of Homebridge version 'latest'.
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge
+ homebridge@0.4.37
updated 2 packages in 3.568s
/root/.homebridge/package.json not found.
Installing plugins from /root/.homebridge/install.sh.
/usr/local/bin/miio -> /usr/local/lib/node_modules/miio/cli/index.js
+ miio@0.15.5
added 96 packages in 8.434s
+ homebridge-re-yeelight@0.0.11
added 1 package in 1.221s
[2018-1-28 17:19:08] Loaded plugin: homebridge-re-yeelight
[2018-1-28 17:19:08] Registering platform 'homebridge-re-yeelight.ReYeelightPlatform'
[2018-1-28 17:19:08] ---
[2018-1-28 17:19:08] Loaded config.json with 0 accessories and 1 platforms.
[2018-1-28 17:19:08] ---
[2018-1-28 17:19:08] Loading 1 platforms...
[2018-1-28 17:19:08] [ReYeelightPlatform] Initializing ReYeelightPlatform platform...
[2018-1-28 17:19:08] [ReYeelightPlatform] [INFO]*********************************************************************
[2018-1-28 17:19:08] [ReYeelightPlatform] [INFO]*                         ReYeelight v0.0.11                         *
[2018-1-28 17:19:08] [ReYeelightPlatform] [INFO]*    GitHub: https://github.com/Zzm317/homebridge-re-yeelight       *
[2018-1-28 17:19:08] [ReYeelightPlatform] [INFO]*                        QQ Group:545171648                         *
[2018-1-28 17:19:08] [ReYeelightPlatform] [INFO]*    Telegram Group:https://t.me/joinchat/EujYfA-JKSwpRlXURD1t6g    *
[2018-1-28 17:19:08] [ReYeelightPlatform] [INFO]*********************************************************************
[2018-1-28 17:19:08] [ReYeelightPlatform] [INFO]start success...
/usr/local/lib/node_modules/homebridge-re-yeelight/Devices/ColorLEDBulb.js:17
    this.device = new miio.Device({
                  ^

TypeError: miio.Device is not a constructor
    at new YeColorLEDBulb (/usr/local/lib/node_modules/homebridge-re-yeelight/Devices/ColorLEDBulb.js:17:19)
    at ReYeelightPlatform.accessories (/usr/local/lib/node_modules/homebridge-re-yeelight/index.js:90:21)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
```

**Comment by Zzm317** [comment]
Please use miio under 0.14.1

**Comment by JrCs** [comment]
Thanks a lot it's working now.
Perhaps it will be good to change the readme to install the right version of miio ?

**Comment by Zzm317** [comment]
I will rewrite the plugin and remove the dependence of miio

**Comment by JrCs** [comment]
@Zzm317 Great !
Thanks for you work !
