### ISSUE TITLE
miio.Device is not a function

### ISSUE THREAD

**Issue by Meryre** [Zzm317/homebridge-re-yeelight#6]
Hello,

I have this error when i run homebridge:
`TypeError: miio.Device is not a function
    at new YeColorLEDBulb (/usr/local/lib/node_modules/homebridge-re-yeelight/Devices/ColorLEDBulb.js:17:24)
    at ReYeelightPlatform.accessories (/usr/local/lib/node_modules/homebridge-re-yeelight/index.js:90:21)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)`

Can you help me please ?

**Comment by Zzm317** [comment]
Can you read the issues before you open an issue?
https://github.com/Zzm317/homebridge-re-yeelight/issues/5

**Comment by Meryre** [comment]
Sorry men... I'm ashamed ...
The answer is here: https://github.com/Zzm317/homebridge-re-yeelight/issues/5
